camunda.bpm.database:
   schema-update: true

camunda.bpm.authorization:
      enabled: true

camunda.bpm:
   default-serialization-format: "application/json"
   
logging.level.org.springframework.web.servlet.mvc.method.annotation:
   RequestMappingHandlerMapping: TRACE
